FROM node:20-bullseye-slim

WORKDIR /app
ENV NODE_ENV=production

COPY package.json package-lock.json ./
RUN npm ci --omit=dev

COPY scripts ./scripts
COPY src ./src
COPY public ./public

CMD ["npm", "run", "render-worker"]